### ISSUE TITLE
What about Svelte 5?

### ISSUE THREAD

**Issue by frederikhors** [probablykasper/date-picker-svelte#101]
Installing 2.13.0 warns with:

```
devDependencies:
+ date-picker-svelte 2.13.0

 WARN  Issues with peer dependencies found
.
├─┬ date-picker-svelte 2.13.0
│ └── ✕ unmet peer svelte@"^3.24.0 || ^4.0.0": found 5.0.0-next.244
```

It works good with Svelte 5 though.

**Comment by probablykasper** [comment]
Not sure if I should add support for beta Svelte versions. Is this a common thing others packages do?

It should still be possible to use with Svelte 5 by running `npm install date-picker-svelte --force` or using [overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides)

**Comment by frederikhors** [comment]
> Not sure if I should add support for beta Svelte versions.

Svelte 5 is almost there: https://github.com/sveltejs/svelte/milestones.

**Comment by probablykasper** [comment]
Ah nice, in that case I'll wait until release

**Comment by KJHJason** [comment]
> Ah nice, in that case I'll wait until release

Svelte 5 is out!

**Comment by probablykasper** [comment]
Published a new version with Svelte 5 support

**Comment by frederikhors** [comment]
What do you think about converting the code to Svelte 5 for faster performances?

**Comment by probablykasper** [comment]
I would accept a PR
