### ISSUE TITLE
`DateTimePicker is not defined` when input is clicked with Svelte 5

### ISSUE THREAD

**Issue by fralps** [probablykasper/date-picker-svelte#102]
Hi there 👋🏻 ,

I am migrating a Svelte 4 project to Svelte 5 and I'm facing an issue with the package (cf screenshot of my console) when I click on the `DateInput`. No problem with the date binding, the date appears correctly in the input.

<img width="494" alt="Capture d’écran 2024-10-25 à 20 20 27" src="https://github.com/user-attachments/assets/4af587eb-6462-499b-9edd-9c1df0558274">

Here is my code:

```svelte
<script>
  import { DateInput } from 'date-picker-svelte';

  let date = $state(new Date);
</script>

<DateInput bind:value={date} />

```

Here are my specs:
- Mac OS Sequoia `15.0`
- Svelte `5.1.2`
- date-picker-svelte `2.14.0`
- Bun `1.1.33` or Node `22.4.1`

No issue when I am using Svelte 4 🤓 

Can you help me on this please? 😊

**Comment by probablykasper** [comment]
I'm not seeing the error: https://svelte.dev/playground/066d0f02c5104a7293ccba0be4ae8636?version=5.1.2

Could you provide a REPL or repro?
