### ISSUE TITLE
Console logging left in library

### ISSUE THREAD

**Issue by nstuyvesant** [probablykasper/date-picker-svelte#108]
Getting this...
$store Wed Nov 27 2024 00:00:00 GMT-0500 (Eastern Standard Time)
logged to my JavaScript Console from DateInput.svelte:21 in the published 2.15.0 version.

<img width="434" alt="image" src="https://github.com/user-attachments/assets/73a7d406-f119-4bdf-b854-93b332c1ef18">

Can a version without the logging be published?

**Comment by probablykasper** [comment]
Oh sorry, fixed

**Comment by nstuyvesant** [comment]
Thanks!
