### ISSUE TITLE
Error: [svelte] reactive_declaration_non_reactive_property 

### ISSUE THREAD

**Issue by akb5566** [probablykasper/date-picker-svelte#109]
Hello, I'm using `date-picker-svelte@2.15.1`. Everything used to work fine. Today I update the `package.json` of my project, and now wherever the page contains `date-picker-svelte`, the following error will show on Chrome Dev Console.

[AppDatePicker.svelte:24 [svelte] reactive_declaration_non_reactive_property
A `$:` statement (node_modules/​.pnpm/​date-picker-svelte@2.15.1_svelte@5.10.1/​node_modules/​date-picker-svelte/​dist/​DateInput.svelte:61:0) read reactive state that was not visible to the compiler. Updates to this state will not cause the statement to re-run. The behaviour of this code will change if you migrate it to runes mode](https://svelte.dev/docs/svelte/runtime-warnings#Client-warnings-reactive_declaration_non_reactive_property)

![image](https://github.com/user-attachments/assets/e90ef914-e5a7-47a9-8d5b-685eed7b47d8)

--

I think it might be the latest `svelte-check@4.1.1` or `svelte@5.10.1` that cause the error. Because this error/warning did not exist before I update the packages.

The culprit might be the `$:` lines in [DateInput.svelte](https://github.com/probablykasper/date-picker-svelte/blob/master/src/lib/DateInput.svelte)

**Comment by probablykasper** [comment]
It's referring to this line:
https://github.com/probablykasper/date-picker-svelte/blob/master/src/lib/DateInput.svelte#L74

I don't see anything about the error in the link you shared, and the link in the screenshot gives a 404 as far as I can tell

Does this occur in Svelte 5.11.2? Please provide a REPL if so

**Comment by akb5566** [comment]
Yeah the error page links to a 404 page now. Probably because Svelte team want to ease the confusion caused by this warning/error message. Please have a read at this thread.
https://github.com/sveltejs/svelte/issues/14532

In short: Svelte will fix the overzealous `reactive_declaration_non_reactive_property` warning in the next release. I'll let you know if this warning persist after next Svelte release. Thanks you.

**Comment by akb5566** [comment]
Can confirm the warning is gone after updating to `svelte@5.11.1`. Thanks you.
