### ISSUE TITLE
stopPropagation on date select

### ISSUE THREAD

**Issue by calebleungg** [probablykasper/date-picker-svelte#13]
Hi there, love your work. A quick one, I'm trying to apply a `stopPropagation` on the date select event but I believe I cant since your `on:select` event is custom.

So far what i've tried.
```svelte
<script>
const select = (e) => {
  e.stopPropagation()
  doSomething()
}
</script>

<DatePicker bind:value={date} on:select={(e) => select(e)} />
```

Any chance we could add a `on:click|stopPropagation` @ https://github.com/probablykasper/date-picker-svelte/blob/791a951df07b62883e99daa3c618740e5c28d786/src/lib/DatePicker.svelte#L291

**Comment by probablykasper** [comment]
Does the event actually propagate?

**Comment by calebleungg** [comment]
From how i'm using it, it seems to be. My use case is
```svelte
<div on:click={openModal} >

  // selecting a date here seems to trigger the openModal function
  <DatePicker bind:value={date} on:select={handleSelect} /> 
</div>
```

**Comment by probablykasper** [comment]
Having stopPropagation for on:select wouldn't prevent your on:click event from doing anything, those are different events. you'll probably have to change how you handle on:click

**Comment by calebleungg** [comment]
Hmmm you could be right, but it seems to stop it when I manually monkey patch with the suggestion in my in initial comment.

It propagates because your `selectDay` method, where you're dispatching the `"select"` event is being fired by an `on:click` for each cell (day)

**Comment by probablykasper** [comment]
The click event from that propagates, not the select event. If you select a date using enter, I doubt your openModal function would fire

**Comment by calebleungg** [comment]
That's exactly right, perhaps my wording was a tad confusion.

**Comment by probablykasper** [comment]
I don't think there's a good way to have an option for it, but you should be able to do something like this:
```svelte
<div on:click|stopPropagation>
  <DatePicker /> 
</div>
```

**Comment by calebleungg** [comment]
All good, thanks for your consideration :)
