### ISSUE TITLE
Do not change current selected date when changing month

### ISSUE THREAD

**Issue by vkurko** [probablykasper/date-picker-svelte#15]
First of all, let me thank you for a great datepicker.

I've noticed a behavior that seems to me unusual. When the month or year is switched, the new date is immediately selected.

For example, May 5 is currently selected. If we move the calendar forward one month, June 5 will be selected immediately, and so on. In my opinion the date should not be selected unless I explicitly click on the new date in the new month. At least this is how the datepicker works in Google calendar or the classic jQuery UI [datepicker](https://jqueryui.com/datepicker/).

Is it possible to change the behavior of your datepicker, or at least make a setting for this behavior?

**Comment by vkurko** [comment]
Well, when the datepicker opens, the user may want to simply look at the available days in other months without changing their selection. It's like a regular `<select>` where you can just scroll to the bottom to see what options are available to choose from.

In the current implementation, if you scrolled the calendar just to see, for example, what the `min` or `max` date is, but you didn't want to change the selection, you would have to scroll the calendar back to return the original value.

**Comment by probablykasper** [comment]
I see, that's fair. I won't be implementing this myself anytime soon, but will leave the issue open
