### ISSUE TITLE
feat: ability to pass name and id as props to set on input field

### ISSUE THREAD

**Issue by TillaTheHun0** [probablykasper/date-picker-svelte#17]
Awesome datepicker for Svelte!

Hopefully i'm not missing anything, but the ability to set `name` and `id` attributes on the `input` element inside of `DateInput`, via props, would be nice.

My use case is that i'd like the component to integrate more seamlessly with form libraries like [felte](https://felte.dev/docs/svelte/getting-started) and it's [`ValidationMessage` component](https://felte.dev/docs/svelte/reporters#using-a-svelte-component), which uses those attributes on the `input` to filter validation messages for display.

My use case is specific, but `id` and `name` are common attributes to set, and native, so i'd suspect this would enable other use-cases as well, without introducing anything opinionated to the api surface.

In lieu of that, I'll need to use the `DatePicker` and then manually bind it to an input, which isn't a big lift or anything, just busy work. Setting `id` and `name` via props on `DateInput` would make the component more turnkey for forms, me thinks :) .

**Comment by probablykasper** [comment]
I don't think adding adding `name` and `id` attributes on the `input` element is a good idea. Presumably you would access the value of the input field, but that value can use any custom format, or just be an invalid value.

It would also only work for `DateInput`, but it's equally valid to use `DatePicker` in a form.

I'm guessing the best way is to have a dummy input, maybe with a unix timestamp as the value?

**Comment by TillaTheHun0** [comment]
I'm not sure I follow. I'm not suggesting to add validation to this lib or anything like that. But the ability to set `id` and `name` would enable folks to bring their own form validation, either manual, or via a form lib like `felte`, instead of having to validate the bounded date string value, separate from the rest of a form. Perhaps I misunderstand your point, if so I apologize 🙂 

A more general use case that isn't validation: Those attributes would also allow using `<label for={name}`>...</label>` to attach labels to an input field, in a form, which is needed for A11y compliance.

**Comment by probablykasper** [comment]
> instead of having to validate the bounded date string value

Maybe I'm misunderstanding you, but `DateInput` doesn't let you bind to the string value. You can only bind to the `value` prop, which is `Date | null`. So if you have your own validation of the string, you would end up just re-implementing `DateInput`'s already existing validation.

> Those attributes would also allow using `<label for={name}`>...` to attach labels to an input field, in a form, which is needed for A11y compliance.

a11y is definitely something that should be figured out, for both `DateInput` and `DatePicker`
