### ISSUE TITLE
Add customizable CSS variables for unavailable dates when using min/max

### ISSUE THREAD

**Issue by Meknassih** [probablykasper/date-picker-svelte#2]
Hello,

Thank you for this great component.

One neat feature that could come in handy is the ability to change the background color of unselectable dates when using the `min` and `max` properties. I think it would be convenient for the user to be able to recognize straight away the days they can click on instead of trying every one of them.

It might be a good first enhancement to gray them out without customizable CSS variables.

**Comment by probablykasper** [comment]
Good idea, though I'd prefer to not have a CSS variable for it. To change the style, you can pretty easily change it using `.cell.disabled` as your CSS selector.

Any thoughts on these?

All equally grayed out:
<img width="259" alt="Screenshot 2021-12-10 at 11 34 41 PM" src="https://user-images.githubusercontent.com/11315492/145649956-45f23bbc-f14c-4897-8a89-a8aa1c6c7071.png">

Extra grayed out:
<img width="260" alt="Screenshot 2021-12-10 at 11 35 36 PM" src="https://user-images.githubusercontent.com/11315492/145649984-3dac981b-96f0-4386-9953-f32e7c7f1aed.png">

Invisible (I think I prefer this one):
<img width="262" alt="Screenshot 2021-12-10 at 11 35 11 PM" src="https://user-images.githubusercontent.com/11315492/145650004-ab4fb389-480f-4bd9-ab41-d0c66e86a3ce.png">

**Comment by probablykasper** [comment]
Made disabled dates invisible in v1.2.0.

If you need to change the style of disabled dates, you can use the CSS selector `.cell.disabled`.
