### ISSUE TITLE
months dropdown doesn't seem to work

### ISSUE THREAD

**Issue by vbilopav** [probablykasper/date-picker-svelte#20]
Click on a months dropdown. List of months appears. Click on any month. Month will not change.

Maybe I'm doing something wrong, or maybe this is by design since same behavior works fine with left and right arrows.

Behavior  can be observed in REPL:
https://svelte.dev/repl/044911429c4b4e659362518d9a5deaae?version=3.49.0

**Comment by probablykasper** [comment]
Are you able to reproduce it on the website? REPL is down atm

**Comment by vbilopav** [comment]
yes
--

**Comment by probablykasper** [comment]
I'm not able to reproduce it. Any more details you can provide?

**Comment by vbilopav** [comment]
I'm not sure what do you mean.

1. Open the repl: https://svelte.dev/repl/044911429c4b4e659362518d9a5deaae?version=3.49.0
2. Click on month dropdown: 
![image](https://user-images.githubusercontent.com/2060047/184289907-60ba83e9-47e6-4ca8-97eb-e5f4dade93ce.png)
3. Click on January (or any other month different then the current August).
4. Month does not change, remains August

**Comment by probablykasper** [comment]
Any errors in the console? What browser and browser version are you using? Does it work on any other browser?

**Comment by vbilopav** [comment]
Tried with Chrome and Edge browsers (the latest versions), same behavior. There are no errors in console.

**Comment by probablykasper** [comment]
Is it just v2.1.0 where this happens, or does it also happen on older ones?

**Comment by vbilopav** [comment]
I don't know, haven't tried it yet. Switched to input type="date" and continued with my project.

**Comment by e0** [comment]
The REPL loaded for me and I'm getting mixed results on macOS.

On Safari, everything works as expected.

On Firefox, the month picker does not change as @vbilopav described. Clicking the steppers (`<` or `>`) or using the keyboard shortcuts (`SHIFT + LEFT/RIGHT`) do seem to work though.

I could reproduce the same behavior on the official [demo page](https://date-picker-svelte.kasper.space/demo) as well.
