### ISSUE TITLE
`valid` prop overridden

### ISSUE THREAD

**Issue by PlopTheReal** [probablykasper/date-picker-svelte#26]
I have a 'start' and 'end' date time picker and I control if the end date is greater than the start date.
I want to reflect that visually by passing the 'valid' prop to the 'end' picker but it seems it's getting overridden by the internal date format check.  Is it possible to do such change? Or is there is any other preferred ways?

**Comment by probablykasper** [comment]
The `valid` prop is mainly there to be read tbh. Would it work for you to use the `min` and `max` props, or just show the user an error message?
