### ISSUE TITLE
Styling for bootstrap

### ISSUE THREAD

**Issue by shadowempire123** [probablykasper/date-picker-svelte#27]
Hi,
I am still a little new to svelte...
Is there a way to style the input, so it is conform with my bootsrap formatiing?
see my example: 
![image](https://user-images.githubusercontent.com/26248866/191020247-30b0dc7c-a745-4807-91ca-d01f7791ea7a.png)

(using sveltestrap)
thx

**Comment by probablykasper** [comment]
Besides the CSS variables, not really, you'd have to override the styles with `:global()`
