### ISSUE TITLE
Allow loading the component without a default value

### ISSUE THREAD

**Issue by nimser** [probablykasper/date-picker-svelte#3]
I'm assuming that if not binding a date with `bind:value={date}`, the placeholder value should be what's rendered in the field before selecting a date.

It's however not the case, as can be seen in [the official demo](https://svelte.dev/repl/044911429c4b4e659362518d9a5deaae?version=3.44.3).

The value in the field at page load defaults to the current date, NOT the placeholder value.

This occurs because the component loads with a default value here:
https://github.com/probablykasper/date-picker-svelte/blob/244b6c5f2ec8b0edbebd35b1b6b2a78390a8a7db/src/lib/DateInput.svelte#L29

Which is set to the current date here:
https://github.com/probablykasper/date-picker-svelte/blob/244b6c5f2ec8b0edbebd35b1b6b2a78390a8a7db/src/lib/DateInput.svelte#L11

I hope we can fix this, as showing a non-date placeholder like `-- / -- / ----` or `Select date` is a pretty common use case.

**Comment by probablykasper** [comment]
Currently `value` is always `Date`, which means that there's never a case where a date isn't selected. If you delete all the text in the input field, you'll see the placeholder.

I think the best way to support this is to allow nullable dates, so I'll close this in favor of #1 (assuming you don't have a better suggestion)
