### ISSUE TITLE
Month dropdown does not work

### ISSUE THREAD

**Issue by RE4LJ0k3R** [probablykasper/date-picker-svelte#31]
Using the arrows to change the months works great, but selecting the month via the dropdown doesn't change anything.
Had the issue on newest version on firefox V106.0.1

**Comment by probablykasper** [comment]
Is it happening in Chrome too?

**Comment by RE4LJ0k3R** [comment]
Yes, it also happens in Chrome.

**Comment by probablykasper** [comment]
It should be fixed now
