### ISSUE TITLE
Add selected date to "select" event

### ISSUE THREAD

**Issue by rogerfar** [probablykasper/date-picker-svelte#32]
When the on:select event is triggered, the detail object is empty:

```
<script lang="ts">
  import { DateInput } from 'date-picker-svelte';

  const handleChange = (event: Event) => {
    console.log(event);
  };
</script>

<DateInput on:select={handleChange} />
```
Is it possible to add the selected date to that event?

**Comment by probablykasper** [comment]
Yeah, that would make sense. `event.detail` should probably be a new date object to avoid it interfering with Svelte stores
