### ISSUE TITLE
weekStartsOn invalid prop for DateInput

### ISSUE THREAD

**Issue by Gildedter** [probablykasper/date-picker-svelte#33]
`DateInput` is missing the prop "weekStartsOn", I'm supplying it via a const object, but my console gives me this warning, I've also checked the component definition

**Comment by probablykasper** [comment]
It works fine for me:
```svelte
<script>
	import { DateInput, DatePicker } from 'date-picker-svelte'
	const locale = {
		weekStartsOn: 4,
	}
</script>

<DateInput {locale} />
```

If you still have the issue, please send a REPL and let me know what browser you're using
