### ISSUE TITLE
d is not always a date type when you fill data from Rest API

### ISSUE THREAD

**Issue by HannanHan** [probablykasper/date-picker-svelte#34]
https://github.com/probablykasper/date-picker-svelte/blob/648561e34815538bd9d6910b3ed9117938e7a0c3/src/lib/DateInput.svelte#L27

we need a string check block over there so that we can convert string to date and then make those checking. Like this:

 ` 
 else if(typeof d === 'string'){              
              let temp = new Date(Date.parse(d));
              if (temp.getTime() !== $innerStore?.getTime()){
                innerStore.set(temp);
                value = temp;
              }
            }
 `

**Comment by probablykasper** [comment]
Not sure about this. I can't really make `value` accept a `string` without making the value `Date | string | null`, which means TypeScript would lead everyone to implement their own handling of `value` being a string.
