### ISSUE TITLE
Clicking on the arrow buttons submits the form (if the component is placed inside a form)

### ISSUE THREAD

**Issue by hubert-ix** [probablykasper/date-picker-svelte#35]
I'm trying to use this component for an upcoming project. Everything integrates very well except for one issue:

When the component is placed inside a form, clicking on the left/right arrows (to navigate between months) submits the form. This has led to some confusing results :-)

The solution would be to either replace the button tags with some div tags, or to add a "return: false;" or "stopPropagation" when clicking on the buttons.

**Comment by probablykasper** [comment]
Thanks for the report, fixed in v2.2.4. The reason is because I used `<button>` without specifying `type="button"`

**Comment by hubert-ix** [comment]
Works perfectly! Thanks for the fast commit.
