### ISSUE TITLE
Min Date Disabled Minute Even On Next Hours

### ISSUE THREAD

**Issue by sellimenes** [probablykasper/date-picker-svelte#38]
In my scenario, a user can't create a new event that is earlier than now. I am using the "min" value for this as new Date().

-- I can't choose an earlier date than I want (this is ok), but I can't choose an earlier minute on the same day even if I choose the next hours.

-- Screen Record link: https://youtu.be/nqiWTvIPqA4

Code block:
`            <DatePicker
                bind:value={date}
                visible="true"
                closeOnSelection={false}
                max = {new Date("2025-12-31 23:59:59")}
                min = {new Date()}
            />`

**Comment by probablykasper** [comment]
Could you provide a REPL reproducing the issue?
