### ISSUE TITLE
Ability to pick time

### ISSUE THREAD

**Issue by zommerberg** [probablykasper/date-picker-svelte#4]
Would be cool to expand the date picker by adding the ability to pick a time, with an optional 24h or 12h time format.
Currently, it is possible to pick a time only by typing the time information within the input.
What would be cool to have is the ability to show the calendar together with a list of times.

Could look similar to a native `datetime-local` input.
![Screenshot_20220107_133501](https://user-images.githubusercontent.com/43446836/148538483-fdff7c3b-3a77-49c1-b024-e4ef93f44a47.png)

**Comment by probablykasper** [comment]
Would be nice, just not sure what the best implementation is 🤔

**Comment by zommerberg** [comment]
As far as the implementation goes here is an idea:

We can create a `TimePicker.svelte` component, that could be put within the `DateInput.svelte` since that looks like something that can be used as a wrapper that shares functions between the TimePicker and DatePicker. The same wrapper is already passing a `$store` variable to the DatePicker so we would pass it the same way to the TimePicker.

The DatePicker and TimePicker do not conflict with each other, nor the input field.


As far as the UI and logic goes:
We can always show 2 columns for time picking. One column would allow us to pick hours, the other would allow us to pick minutes.

Only when `12h time format` is selected we would additionally show `PM / AM` column.
Would be nice to a property we pass to `DateInput` to force a certain format. `24Hours`(default:false?)
Would be nice to disable/enable time picking. `timePicker` (default:true)

**Comment by probablykasper** [comment]
I'm not sure about the column thing, it seems a bit slow to use.

I'd say 24-hour should be default as about 70% of the world seems to use it, and ISO8601. Might be possible to get a user preference through a JS API though

**Comment by zommerberg** [comment]
Any ideas for an alternative? One thing that comes to mind is creating a clock:
![Screenshot_20220110_004222](https://user-images.githubusercontent.com/43446836/148704144-40940873-9cc9-4e12-979c-c3c5b82f9789.png)

But it is too big.

Another thing would be to create text inputs but we already have that... Maybe we don't even need this feature lol

**Comment by probablykasper** [comment]
[Blueprint's Date input](https://blueprintjs.com/docs/#datetime/dateinput) is one that does let you add input elements for the time:

![](https://user-images.githubusercontent.com/11315492/148704475-988dd8dc-4c89-4b50-a100-ad2a34dd198e.png)

**Comment by zommerberg** [comment]
I love that, seems simple and easy to use

**Comment by wighawag** [comment]
Hey, was looking for such date component with time input. 
Anyone working on that feature ?

**Comment by probablykasper** [comment]
Released in [v2.9.0](https://github.com/probablykasper/date-picker-svelte/releases/tag/v2.9.0)
