### ISSUE TITLE
Feature Request: Ability to choose date range

### ISSUE THREAD

**Issue by chanmathew** [probablykasper/date-picker-svelte#40]
Hi there, would love for this lib to be able to support the ability to select a date range. There's a serious lack of date picker components for Svelte / Sveltekit and would love to see this added!

**Comment by probablykasper** [comment]
I'm not sure if it's something I'd want added. Selecting ranges in one date picker has always felt clunky to me. I'd probably use two date pickers instead

**Comment by Gildedter** [comment]
> Hi there, would love for this lib to be able to support the ability to select a date range. There's a serious lack of date picker components for Svelte / Sveltekit and would love to see this added!

You can do something like this, its a bit unwieldy but it works:
```
<div class="col flex-grow-1" id="lhs">
    <DateInput
        {...datePickerFormat}
        bind:value={dateStart}
        max={maxStart}
    />
</div>
To
<div class="col flex-grow-1" id="rhs">
    <DateInput
        {...datePickerFormat}
        bind:value={dateEnd}
        min={dateStart}
        max={maxEnd}
    />
</div>
```
