### ISSUE TITLE
Outline 'today' on date picker

### ISSUE THREAD

**Issue by BrianCastor** [probablykasper/date-picker-svelte#46]
Enhancement request: It would be great to outline today's date on the calendar to make it easier to identify. Similar to how Flatpickr or MUI style the today item.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/16365884/213085080-03b237e3-9994-496b-b34e-1b769067c784.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/16365884/213085206-590b1937-b5e3-4154-91c2-73d347f5077e.png">

**Comment by probablykasper** [comment]
Good suggestion

**Comment by VladimirLakodei** [comment]
@probablykasper could you please review and merge this PR. It is really useful feature.
![image](https://user-images.githubusercontent.com/56593309/223947539-c265cc11-ad4c-4a3f-802b-cec51dbb031e.png)
![image](https://user-images.githubusercontent.com/56593309/223947628-66fba446-f8f3-40c3-a9bd-ab774aa117bd.png)
