### ISSUE TITLE
Add inputs to DatePicker

### ISSUE THREAD

**Issue by nicholasvperry** [probablykasper/date-picker-svelte#47]
I love your datepicker. I think it is great!

I would love to be able to add some input values to the DatePicker Calendar. 

I have a current calendar that allows us to add our own inputs. I also would like to have the option to add a button at the bottom. I would be able to handle all the bindings myself but just being able to add things below  the calendar.

My thoughts are writing something like this and having the ability for the button to close the calendar once clicked.

`<DatePicker>
<select>
    <option value="">--Please choose an option--</option>
    <option value="foo">Foo</option>
    <option value="bar">Bar</option>
</select>
    <button>test</button>
</DatePicker>`

![image](https://user-images.githubusercontent.com/90103179/214939126-66a50a0b-14c2-47f5-afc4-664de73e3b20.png)

**Comment by probablykasper** [comment]
Sure, that sounds useful
