### ISSUE TITLE
When passing browseWithoutSelecting and a value, month/year selector doesn't work

### ISSUE THREAD

**Issue by marcnajera** [probablykasper/date-picker-svelte#50]
Hey, thanks for your work, the component is amazing.

I've seen that whenever you pass `browseWithoutSelecting` and a `value`, the month and year selectors (arrows included) don't work.

Here's  a REPL replicating the bug: https://svelte.dev/repl/2c23cf5f7ae048e1808948bf1b3d2860?version=3.57.0

**Comment by probablykasper** [comment]
Thanks for the report. Would appreciate a PR

**Comment by probablykasper** [comment]
Fixed in v2.4.1
