### ISSUE TITLE
Conflicts in svelte resolve

### ISSUE THREAD

**Issue by DanielAlcaraz** [probablykasper/date-picker-svelte#52]
Hi,

I upgraded my project dependencies and some new warnings appeared. This is the message:
`[vite-plugin-svelte] WARNING: The following packages use a svelte resolve configuration in package.json that has conflicting results and is going to cause problems future.`

Here there is more info about the conflicts by the **vite-plugin-svelte** team:
[https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve](https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#conflicts-in-svelte-resolve)

**Comment by probablykasper** [comment]
Should be fixed in v2.4.0 (lmk if not)
