### ISSUE TITLE
Not so dark-mode.

### ISSUE THREAD

**Issue by TonyDWKR** [probablykasper/date-picker-svelte#57]
I have my date-picker configured to be in dark mode with some color tweaks. 
But the combo box that contains the lists of the months is in light mode and the text not displaying correctly, shadowing the ones avaible and showing the unavaible like they're avaible.

Also, i would like to ask how to change the names of the months, because i need to put it on spanish, but can't seem to find the way to do it. If someone can be so kind to help me :).

Thanks. 

![Screenshot_1](https://user-images.githubusercontent.com/118015228/236668372-757f4108-2ee6-4c3f-92c0-4b836c48d050.png)

**Comment by probablykasper** [comment]
The dropdown is native, the date picker doesn't have any control of that afaik. Maybe you need to set the color-scheme, otherwise idk.

See the  docs on the `locale` property for how to set the locale
