### ISSUE TITLE
Allow standard html attributes to be passed to `input`

### ISSUE THREAD

**Issue by p4bloch** [probablykasper/date-picker-svelte#59]
Hello. I don't have a ton of experience in Svelte yet so maybe this is not an issue, but it would be great to allow any valid html attribute to be applied to the inner `input` this library exposes. Some examples I can think of

- `id`
- `aria-` attributes
- `data-` attributes

Is there an easy way to do this in Svelte or one would need to create wrapper proprs for all of them? This doesn't scale well with dynamic ones like `data-` which are custom (valid) attributes. Here's an [example of how Vue handles this](https://vuejs.org/guide/components/attrs.html#attribute-inheritance-on-multiple-root-nodes)

Happy to put up a PR once we agree on the strategy here

**Comment by p4bloch** [comment]
After some proper look at the Svelte documentation, I found https://svelte.dev/docs#template-syntax-attributes-and-props

> `$$restProps` contains only the props which are not declared with export. It can be used to pass down other unknown attributes to an element in a component. It shares the same optimisation problems as $$props, and is likewise not recommended.
>
> `<input {...$$restProps}>`

I think this could work.

**Comment by probablykasper** [comment]
I'm not too sure about this, what's your use case? I wouldn't want people to for example add a `name` because that would be a weird format to use and it would only work with the input

**Comment by p4bloch** [comment]
@probablykasper the most straightforward use case I can think of is adding an id to be able to semantically use a `label`

```html
<label for="some input>
<input id="some input" />
</label>
```

**Comment by probablykasper** [comment]
We could add an id prop

**Comment by elton2048** [comment]
It is better to allow extra class attributes to be in `<input>` element too for layout customization using like tailwind css.

**Comment by probablykasper** [comment]
`class` is supported

**Comment by elton2048** [comment]
> `class` is supported

I am not sure if this is the case, but the source doesn't show the class for the `<input>` element getting the class attributes (I am the `<input>` element inside the `<div>` wrapper element).
```html
<input
    class:invalid={!valid}
    type="text"
    value={text}
```

**Comment by probablykasper** [comment]
It's here:
https://github.com/probablykasper/date-picker-svelte/blob/9ff4ca0835a7bb88c7c2bd4182bc4b96eb88428e/src/lib/DateInput.svelte#L51-L53

`export let class` doesn't work because `class` is a JavaScript keyword.

Also, Svelte doesn't support `class:` for components, see https://github.com/sveltejs/svelte/issues/5236 and https://github.com/sveltejs/svelte/issues/5218

**Comment by spy16** [comment]
Apart from other points @elton2048 mentioned already, to make it work well with forms (for use with SvelteKit actions) for example, having the ability to set `name` is useful. And being able to set all the `aria-` attributes and other attributes (except where it would interfere with the custom logic of the component would be good i think).

This way, it would be an enhanced version of `input type="date"` and allow all the patterns that we can use with it.

**Comment by probablykasper** [comment]
> Could you elaborate on this please? To make it work with forms, this is needed.

The input is a customizable user-facing value, not a data value. Parsing on the server would get complicated, especially for user-dependent formats. It also wouldn't work for the `DatePicker` component.

I'd be happy to have other attributes that make sense, like `id`.

Would be good to have built-in `aria-` attributes

**Comment by jhoddevik** [comment]
So ... how can we use this in forms?

**Comment by probablykasper** [comment]
By binding to the date value and putting it in an input element

**Comment by eberhapa** [comment]
> We could add an id prop

That's exactly what I need because of Accessibility reasons to make <label for=""> possible.

**Comment by p4bloch** [comment]
It seems we have some alignment that at least `id` and `aria-` attributes are needed to have some basic accessibility support.

I think the remaining big item is about the implementation strategy. The way I see it we have at least two potential solutions

1- Expose specific, hardcoded attributes for `id`, and all the `aria-` attributes
2- Use something like I suggested initially `<input {...$$restProps}>` which would allow us to future-proof this library and even support valid custom attributes like `data-` ones.

Any pros/cons you all see here? cc @probablykasper

**Comment by eberhapa** [comment]
What's the problem of giving the possibility to pass all props? It would be the most flexible way.

**Comment by probablykasper** [comment]
I don't want to allow all props for the reasons I already mentioned. `id` and `aria-` attributes make sense

**Comment by happysalada** [comment]
Could we also add a "required" attribute to be passed.
if used in a form and the user didn't input, but is trying to submit, most browser have auto focuse on the required field. This would be nice to have.

**Comment by probablykasper** [comment]
`required` and `id` are now supported. For `name`, see
- https://github.com/probablykasper/date-picker-svelte/issues/44

About `aria-`, feel free to open a new issue with more concrete details
