### ISSUE TITLE
Setting text class in DateInput?

### ISSUE THREAD

**Issue by Whaleplane** [probablykasper/date-picker-svelte#62]
Is there a way to use a text style class on the DateInput component? Here is what I am trying:

```svelte
<div>
	<DateInput bind:value placeholder="eg. 2023-06-01 12:34:56" class="text-gray-400" />
</div>
```

But the class is not being applied to the text in the input.

I see in `src/lib/DateInput.svelte` that the class is being applied to the div that's around the input:
```svelte
<!-- svelte-ignore a11y-no-static-element-interactions -->
<div class="date-time-field {classes}" on:focusout={onFocusOut} on:keydown={keydown}>
  <input
```

So I tried adding a new style that applies the original style to an input (using the @apply directive from tailwind):
```svelte
<style>
	.text-gray-400-input input {
		@apply text-gray-400;
	}
```

But this requires a class directive `class:` instead of `class="` which looks like it's not supported by this component.

Is there currently no way to customize the font in the DateInput? Or am I missing something obvious?

**Comment by probablykasper** [comment]
Svelte styles are scoped to the component, so you need to use `:global()` https://svelte.dev/docs/svelte-components#style

There are also CSS variables you can use: https://date-picker-svelte.kasper.space/docs#css-variables
