### ISSUE TITLE
Feature Request: Slot Support for Day Customization

### ISSUE THREAD

**Issue by GagnDeep** [probablykasper/date-picker-svelte#65]
Currenly there is no way to disable some days from being selected or to highlight some day. This functionality could be implemented within library but a quick way to allow this would be just to allow passing slot for the day in the compoment.

**Proposed Behavior**
```svelte
<DatePicker let:calendarDay>
  <span>{calendarDay.number}</span>
</DatePicker
```

**This will make something like this possible**
```svelte
<DatePicker bind:value let:calendarDay>
  <span
    class:highlighted-day={isHighlighted(calendarDay)}
    class:disabled-day={!isHighlighted(calendarDay)}
    on:click={(event) => {
      if (!isHighlighted(calendarDay)) {
        event.preventDefault();
        event.stopPropagation();
      }
    }}
    class="h-full w-full flex items-center justify-center"
  >
    <span>{calendarDay.number}</span>
  </span>
</DatePicker>
```

**Comment by probablykasper** [comment]
It seems a bit complex to use. I think a [isDateDisabled](https://github.com/probablykasper/date-picker-svelte/issues/29#issuecomment-1271812484) prop would be better

**Comment by GagnDeep** [comment]
yes a prop based solution for disabling date would be much simpler.

But still adding a slot support for day would open a lot of customizations options for day, like added a tooltip to that date or maybe having some custom background for an individual date which is not possible currently. 

Another potential way could be to support passing a `dateComponent` as a prop or support some `getDateClass` prop, that allows to set a custom class to a particular date

**Comment by probablykasper** [comment]
I think if we go down that route we'll have slots for everything, and I'm not sure that's too great
