### ISSUE TITLE
Input field showing date only, no date-time?

### ISSUE THREAD

**Issue by bluepuma77** [probablykasper/date-picker-svelte#75]
Is it possible to remove the time part in the input field, set GMT/Zulu time by default?

![date-picker](https://github.com/probablykasper/date-picker-svelte/assets/5221187/02e1df9e-9a1e-4b08-8521-e0d97e748b3c)

**Comment by probablykasper** [comment]
Yes, you can set a custom format. More info here: https://date-picker-svelte.kasper.space/docs

**Comment by bluepuma77** [comment]
@probablykasper Found the issue: when date is not set, the component will display a grey default value with date+time, even when `format="dd.MM.yyyy"` is set.

**Comment by probablykasper** [comment]
Ah yeah, you can set the placeholder for that
