### ISSUE TITLE
Add name and class property to DateInput

### ISSUE THREAD

**Issue by bluepuma77** [probablykasper/date-picker-svelte#76]
It would be great to have a name and class property on `DateInput`. That would enable manual input/submit when having disabled JS and use something like bootstrap CSS to enable styling of the input box and to enable a red box upon wrong input.

**Comment by probablykasper** [comment]
There actually is a `class` property on `DateInput`.

I can't add `name` to the actual `<input>`, but there could be a fake input for form submission. What format should the value be, unix timestamp?

**Comment by bluepuma77** [comment]
Great to have `class` already. Value I would set to ISO format.

**Comment by bluepuma77** [comment]
Ah, but the class is on the parent, not on the input field.
<img width="497" alt="date-picker-class" src="https://github.com/probablykasper/date-picker-svelte/assets/5221187/44fa9f9f-dcba-4fb7-982f-b9a4acecd735">

So the input field is not getting the right CSS
<img width="568" alt="date-picker-input" src="https://github.com/probablykasper/date-picker-svelte/assets/5221187/e6ed810e-a135-41ff-ab7b-3caf053fcd57">

**Comment by bluepuma77** [comment]
@probablykasper Here a proposal: add properties `name` and `inputClass` (or `innerClass`) to input tag.

**Comment by probablykasper** [comment]
Adding `name` to the input tag would cause lots of headaches, so I would only go with the fake input solution.

It would be nice if there's a way to avoid having multiple `class` properties

**Comment by bluepuma77** [comment]
I doubt that you can avoid multiple class properties. Some need to go to the outer div, some to the input field if displayed. [svelty-picker](https://github.com/mskocik/svelty-picker) supports "inputClasses" for "input css class string".

What's the issue with the name property? Can't it simply be:
```
<script lang="ts">
    export let name = ''
</script>

<input name={name} />
```

**Comment by probablykasper** [comment]
See
- https://github.com/probablykasper/date-picker-svelte/issues/44

**Comment by bluepuma77** [comment]
It might also make sense to have an `<DateInput inputId="id" />` to be able to use `<label for="id" />` for accessibility.

Maybe right next to `<DateInput inputClass="form-control" />` ;-)

**Comment by bluepuma77** [comment]
My last try regarding name: Maybe just use `<DateInput inputName="creation" />` to assign a name to the input field as backup when SSR is used and no JS on client is allowed. 

I don't worry about the format, as it is written in the input already, so the server can deal with it. And if you really want a fixed format, the `Date().toISOString()` is probably the common standard in JS/Node/JSON.

**Comment by bluepuma77** [comment]
I [forked](https://github.com/bluepuma77/date-picker-svelte/commits/master) and added a type check and `inputClass`, `inputStyle`, `inputName`. You want a pull request?

**Comment by probablykasper** [comment]
Nice! No thanks, I'd need to think about it

**Comment by wwmike** [comment]
+1
It would be a nice feature, I could solve it only this way:

```
<style lang="postcss">
	:global(.birthdayPlaceholder input) {
		@apply !w-2/3 !p-3 !pl-5 !my-4 !text-sm !text-gray-400 !border-solid !shadow-inner !placeholder-inherit !bg-gray-50;
	}
</style>
```

which looks terrible.
