### ISSUE TITLE
Enhancement Request: Implement 'readonly' Attribute in Input feild

### ISSUE THREAD

**Issue by ajay-prabhakar** [probablykasper/date-picker-svelte#79]
I propose enhancing the date picker component in Svelte by ensuring a 'readonly' attribute, enabling users to conveniently select dates solely via the date picker interface, thus preventing manual text input for a smoother and error-resistant user experience.

**Comment by probablykasper** [comment]
Strongly disagree with that since the date input requires fewer key presses and allows copy pasting

**Comment by ajay-prabhakar** [comment]
@probablykasper Yes we can make that as default but to configure we can expose one attribute right
