### ISSUE TITLE
Year is maxing out at 2024

### ISSUE THREAD

**Issue by gregg-cbs** [probablykasper/date-picker-svelte#84]
Hey this is an awkard one.

I am passing in a date for year 2025 but the date picker is maxing out at 31 Dec 2024.

![image](https://github.com/probablykasper/date-picker-svelte/assets/57114335/c1e8b4db-8f44-46d0-8843-8cc1e40c7086)

Version: 2.10.1

**Comment by gregg-cbs** [comment]
Right I see I have to set a max. Any thoughts on making the max default higher then the current year?

**Comment by probablykasper** [comment]
No, sorry, think the current default is ok. I don't think it would be worth a breaking change
