### ISSUE TITLE
Value does not react when updating time, only when updating date

### ISSUE THREAD

**Issue by SkepticMystic** [probablykasper/date-picker-svelte#86]
Hi there.
Thanks for this component :)

When testing the component in your docs, the chosen value reacts when selecting a date _and_ when selecting a time. You can see the value changing when you update the time.

But when I use the component in my own project (with `bind:value`), it only reacts when a _date_ is chosen, but not when the time is updated. Here is how I'm using it, is there something wrong or incompatible?

```svelte
<DateInput
          timePrecision="minute"
          format="yyyy-MM-dd HH:mm"
          browseWithoutSelecting={true}
          min={new Date(Date.now() + 5 * 60_000)}
          bind:value={date}
        />
```

**Comment by probablykasper** [comment]
Could you share a REPL and screen recording to illustrate the problem?

**Comment by SkepticMystic** [comment]
Huh, I updated from `2.10.1` to `2.11.0` and it works now.
Basically, in the following code, the console.log would only trigger when clicking on a calendar day, but not when changing the _time_ (from say 11:00 to 11:30).

```svelte
<script>
	import { DateInput } from "date-picker-svelte";
	
	let date = new Date()
	$: console.log(date.toISOString())
</script>

<code>{date.toISOString()}</code>

<DateInput
          timePrecision="minute"
          format="yyyy-MM-dd HH:mm"
          browseWithoutSelecting={true}
          bind:value={date}
        />
```

The same thing still happens if you hook into `on:select`, though.
If you do that instead of binding, the component only seems to dispatch the `select` even when clicking on a calendar day, but not when changing the time

**Comment by probablykasper** [comment]
I see, could you create a [REPL](https://svelte.dev/repl)?

I wonder if `select` fires when changing the month/year, and how we should handle `closeOnSelect`

**Comment by SkepticMystic** [comment]
Sure, I believe this captures the issue: https://svelte.dev/repl/146e9af6e3db4a5784fdcd068da9af9a?version=4.2.12

**Comment by probablykasper** [comment]
Gotcha, I'd say `select` is intended specifically for when you select a date, not when changing the time, month or year

**Comment by SkepticMystic** [comment]
I mean, I get you. Otherwise it would dispatch too frequently. But it's quite difficult to communicate this to users that, if they just want to change the time and not the date, they still have to click the selected date to trigger the update event.

**Comment by probablykasper** [comment]
Yeah but if you have `closeOnSelect`, then:
1. it would only close on select _sometimes_, if `select` fires when you update time/month/year
2. or it would close when you just update the time/month/year

both of those really suck imo

**Comment by SkepticMystic** [comment]
Yeah, fair enough. I'll try make it work with bind instead.
The original issue is also resolved, so I'll close this out. Thanks for your help!

**Comment by probablykasper** [comment]
Potentially `select` could be fired when the date picker is defocused, and an `input` event could be fired anytime the user changes something

**Comment by SkepticMystic** [comment]
Yeah, that could work!
