### ISSUE TITLE
Support for Year-Month precision?

### ISSUE THREAD

**Issue by mkelandis** [probablykasper/date-picker-svelte#9]
It might be nice to show an abbreviated version of the picker when the desired precision is year-month, that excludes the calendarDay selection. Would need a way to configure the desired precision when invoking the component (can the format be used?) Dropping this here to open up for discussion.

**Comment by probablykasper** [comment]
At that point you'd just have a date picker with 2 dropdowns. I feel like at that point you should just make your own 2 dropdowns instead
