### ISSUE TITLE
Set autocomplete to off

### ISSUE THREAD

**Issue by gianarb** [probablykasper/date-picker-svelte#93]
Hello

Thank you for this date picker, I would like to turn autocomplete off but I don't think this is supported.
I am happy to contribute to it if you think this is a good idea and I am sorry if it is already a supported feature but I can't figure out how to it.

**Comment by probablykasper** [comment]
I can't think of a reason to want autocomplete enabled, so would make sense to turn it off completely yeah. Feel free to submit a PR
