### ISSUE TITLE
Format not applying to initial value

### ISSUE THREAD

**Issue by Alfagun74** [probablykasper/date-picker-svelte#95]
I found a big problem when using this library, but I really want to use it. Here's how I'm trying to use it:

```
<script>
const startDate = new Date();
</script>

<DateInput
  disabled
  class="customDatePickerClass"
  bind:value={startDate}
  timePrecision="minute"
  format="dd.MM.yyyy HH:mm" />
```

But the result I get isn't what I expected. It looks like this:

![image](https://github.com/probablykasper/date-picker-svelte/assets/22225051/4c348f5a-2b62-483d-8eb7-d9e7ac2e19c4)

What I want is for it to show the initial date and time the way I asked for, like this:

![image](https://github.com/probablykasper/date-picker-svelte/assets/22225051/733a8b5a-5e28-4573-b48d-c3f9bb184dc4)

**Comment by probablykasper** [comment]
Could you provide a REPL?

**Comment by Alfagun74** [comment]
nevermind i was just confused by your confusing ass placeholder again 😉
