### ISSUE TITLE
Seemingly random placeholder

### ISSUE THREAD

**Issue by Alfagun74** [probablykasper/date-picker-svelte#96]
"2020-12-31 23:00:00" is a very random and confusing placeholder if none is set. Instead it should say either nothing or "Choose..." or something like that

**Comment by probablykasper** [comment]
If it says "Choose...", you wouldn't know what format to type out. It's a text field, not a button, so I think an example is good

**Comment by Alfagun74** [comment]
Seriously? Your so-called example just confuses folks. People hit me up because they thought the input field's already stuffed with some **random** date. 

It's not even hinting that they still need to pick a date and time. And your argument is that it is a text box? Ain't nobody typing in a date-time string like it's some love letter; they're selecting it by clicking through the damn calendar.

**Comment by probablykasper** [comment]
No need to be rude. I don't wanna spend my spare time with people acting like that, so you can either apologize or get banned

**Comment by Alfagun74** [comment]
Oh, what a tragedy it would be if you were to ban me! My existence would surely crumble without the sheer joy of using this picker library.
